# Use the official PostgreSQL image from Docker Hub
FROM postgres:latest

# Set the environment variables for PostgreSQL
ENV POSTGRES_DB dataengineer
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD barabai123

# Expose the default PostgreSQL port
EXPOSE 5432
