version: '3'

services:
  postgres:
    image: postgres
    container_name: my_postgres
    environment:
      POSTGRES_DB: dataengineer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "barabai123"
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
